catch aws-cli snap package

diff --git a/nagios/check_cloudwatch b/nagios/check_cloudwatch
--- a/nagios/check_cloudwatch
+++ b/nagios/check_cloudwatch
@@ -9,6 +9,7 @@ INSTANCEID=$(_meta instance-id)
 AZ=$(_meta placement/availability-zone)
 [[ -n "$INSTANCEID" && -n "$AZ" ]] || _die "Can't access instance meta-data."
 export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-${AZ%[a-z]}}
+export PATH="$PATH:/snap/bin"
 
 PROCNAME="${1:-/usr/sbin/nagios}"
 VALUE=$(_procs $PROCNAME)
@@ -25,5 +26,6 @@ then
   [[ $VALUE = 0 ]] && exit 1
   exit 0
 else
+  echo "CloudWatch CRITICAL: aws command failed status=$?"
   exit 2
 fi
